function Hd = buter
%BUTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.5 and DSP System Toolbox 9.7.
% Generated on: 23-Jan-2021 07:22:21

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 70;  % Sampling Frequency

Fpass = 28;             % Passband Frequency
Fstop = 28.5;            % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 1e-05;           % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
